### ISSUE TITLE
Consider a koa version

### ISSUE THREAD

**Issue by Mitranim** [dchester/epilogue#100]
[koa](http://koajs.com) is a superior alternative to Express. You might want to consider implementing a version of `epilogue` compatible with it.

**Comment by TooBug** [comment]
any update?

**Comment by mbroadst** [comment]
hey guys, unless there is a way for koa to "just work" with the current design of epilogue, I don't expect a rewrite of the module using generators any time soon unfortunately. Too much of the current design is built around existing concepts in express and restify, and frankly I have basically zero experience with koa. I'm not against integrating support if it's not a major/invasive change however.

**Comment by TooBug** [comment]
koa has a method `app.callback()`, it seems that the return value is the raw `app` by `http.createServer()`, so I wonder if epilogue could consider supporting this. Nothing to do with koa framework or generator function.

**Comment by m4rcelofs** [comment]
Has anyone tried to use [koa-connect](https://github.com/vkurchatkin/koa-connect)?
