### ISSUE TITLE
Does the REST api handle multiple conditions and inequalities

### ISSUE THREAD

**Issue by mark-lester** [dchester/epilogue#110]
I want to fetch all the stops within a given rectangle (the current view of the map)
Can I cook this up with a URL on the existing framework or do I need to hatch my own API call.
I saw the search/operator doco which is obviously what I need if I need to make this, I was just checking that it's up to me to make a special resource.
It would be nice to be able to go something like

    /Stops?lat=$gt$:min_lat&lat=$lt$:max_lat&lon=$lt$:min_lon&lon=$lt$:max_lon

**Comment by mark-lester** [comment]
I have this working, 
```
http://localhost:3000/api/Stops?lat=34.05$lt&lat=35.05$gt
```
but not really as the conditions appear to being orred, so I just need to work out how you "and" them.
obviously this will crack up if you want to do too much, but a series of filters with operands is a handy thing.

**Comment by mbroadst** [comment]
@mark-lester can't you create a milestone that pulls these values out of the query string before whatever operation (list in this case), and adds them to the criteria that way?

```
stopsResource.list.fetch.before = function(function(req, res, context) {
  // check req here, pull out things you want
  // add each of those things to `context.criteria`
  // remember to call `delete req.whatever` so its not processed again in the actual controller

  return context.continue;
});
```

**Comment by mark-lester** [comment]
yes I can, I will go learn. I need to implement row level access control so I need to get into all that stuff anyway.

**Comment by mark-lester** [comment]
@mbroadst I stared at 
```
function(function(req, res, context) {
``` 
and decided I knew less about this language than when I started. But it doesnt compile, and
```	
	_.each(sequelize.models,function(model){
		resources[model.name] = epilogue.resource({
			model: model,
			associations:true,
			pagination:true,
			endpoints: [config.apibase+'/'+model.tableName, config.apibase+'/'+model.tableName+'/:id']
	});
	resources[model.name].list.fetch.before=multiConditional;
```
doesnt seem to get called either.
I've hived all my stuff into it's own space, and I've even added aggregates, so in theory I should also be able to go
```
/api/Stops?attributes=min(lat),min(lon),max(lat),max(lon)
```
and get back 
```
{min_lat:34.59,min_lon:-106.75,max_lat:35.24,max_lon:-106.48}
```

**Comment by mbroadst** [comment]
@mark-lester oops sorry!! hah that was clearly a typo, you should be doing:

```
stopsResource.list.fetch.before(function(req, res, context) {
  // check req here, pull out things you want
  // add each of those things to `context.criteria`
  // remember to call `delete req.whatever` so its not processed again in the actual controller

  return context.continue;
});
```

or in your case, if you've assigned a function that has a signature `(req, res, context)` to `multiConditional `, then you should do: `stopsResource.list.fetch.before(multiConditional)`

**Comment by mark-lester** [comment]
@mbroadst it's been a long day, thanks as ever

**Comment by mbroadst** [comment]
@mark-lester no worries, sorry for the shinfo there. We can close this guy out now?

**Comment by mark-lester** [comment]
yes, it's a feature request I guess. I have this working, including attribute specification.
I've edited this line https://github.com/dchester/epilogue/blob/master/lib/Controllers/list.js#L39
to go
```
  options.attributes = context.attributes || options.attributes || this.resource.attributes;
```

**Comment by mbroadst** [comment]
Well that's an easy one to fix. Take a look a few lines above, what you want to be setting in your milestone/middleware is `context.options.attributes` not `context.attributes`

**Comment by mark-lester** [comment]
ta. but yes close this out, one way or another i am fixed.
