### ISSUE TITLE
Is epilogue supposed to work with strings as ids?

### ISSUE THREAD

**Issue by philotas** [dchester/epilogue#118]
When I declare a string as my id column (primaryKey: true) then I cannot GET /resources/sss

I get en error:

`Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: NaN`

You are obviously always expecting a number?

Is there a reason for this limitation? Or is this a bug ?

**Comment by mbroadst** [comment]
Hm, I don't see anything that would prevent you from using a string id. Can you show me more of your setup (model as well as resource definitions)?
