### ISSUE TITLE
How to make some fields read-only.

### ISSUE THREAD

**Issue by luckypur** [dchester/epilogue#129]
excludeAttribute dose not works with Post request. Like suppose there is  'isSuperuser' field in user table which should not be open to change through any Post request. I understand that we can do it with milestones and hooks but a simple list field(readOnlyAttribute) in resource config would be great.

**Comment by mbroadst** [comment]
@luckypur this would be incredibly easy to add to the create controller. If you submitted a fix with a test I would gladly accept it, thanks for your interest!

**Comment by luckypur** [comment]
@mbroadst please check the PR [#131](https://github.com/dchester/epilogue/pull/131)
