### ISSUE TITLE
Possibly unhandled (<Error: ER_ROW_IS_REFERENCED: Cannot de...>, no stack trace)

### ISSUE THREAD

**Issue by NatuMyers** [dchester/epilogue#143]
I literally copied the code from epilogue's npm page, and it doesn't work.I just updated my db credentials and I was greeted with:

`Possibly unhandled (<Error: ER_ROW_IS_REFERENCED: Cannot de...>, no stack trace)
`

**Comment by mbroadst** [comment]
@NatuMyers what code did you copy, what database are you using, etc? I can guarantee that the code on the front page works to some extent as we have integration tests that are run using essentially the same boilerplate (as recently as 15 hours ago).

**Comment by NatuMyers** [comment]
I copied "Getting Started" from https://www.npmjs.com/package/epilogue
Here is the repo of the code https://github.com/NatuMyers/A.M.E.N.SQL-Stack
The only difference is I imported the models instead of defining them inline.
I also alternate between that and a "TypeError: Cannot convert undefined or null to object" error. Please help I've been working on this for hours and hours.

**Comment by mbroadst** [comment]
@NatuMyers not sure where to start here, your repo doesn't even start for me. As an initial FYI, it's uncommon to publish your `node_modules` directory to your git repo, also your dependencies seem a bit all over the place (you seem to mix grunt and gulp, and there are a number of failed peer dependencies)

Now to the code: you are providing a function to epilogue as if it were a Model reference [here](https://github.com/NatuMyers/A.M.E.N.SQL-Stack/blob/master/app.js#L65). I think what you meant to do was:

```
// Create REST resource
var userResource = epilogue.resource({
  model: db.User,
  endpoints: ['/users', '/users/:id']
});
```

You have rolled your own model loading code here, but failed to use it properly. If you _had_ copied the code from the README, it would indeed work :smile:
