### ISSUE TITLE
Wrap default response in an object

### ISSUE THREAD

**Issue by jgutix** [dchester/epilogue#149]
To prevent JSON hijacking, instead of `[{"field1": "value1", ...}, ...]` the default successful response should look like: `{"data": [{"field1": "value1", ...}, ...]}` as suggested here: https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside

**Comment by mbroadst** [comment]
@jgutix this is easily solved by using milestones, so you can configure your data to look however you want it.  I think it would be helpful to include a few middlewares (such as a middleware that just plainly wraps the response data in an object like you suggest), or perhaps something a little more useful like a JSON schema middleware.  As far as changing the default response, I don't think that's an option considering the age of the module, it would be too much of a breaking change imho.
