### ISSUE TITLE
Filtering by date?

### ISSUE THREAD

**Issue by jblaketc** [dchester/epilogue#169]
I'm having to do multiple filters on records, mostly foreign key matches, so I've just moved all the filters to context.criteria so that I could get equal functionality. 

````javascript
	if(_.isObject(req.query.filter) && req.query.filter != null) {
					
					context.criteria = req.query.filter;
					delete req.query.filter;
					


				}

````

I also have to filter by CreatedOn, so I'm not sure how I would do that. Filter looks like:

````javascript
{
    DropdownId: 2,
    CreatedOn: '2016-06-13'
}
````
What do I have to do to the CreatedOn obj value to get it to filter on that property as well, because obviously in the database, CreatedOn is a datetime.

Thanks!

**Comment by mbroadst** [comment]
@jblaketc we use `find` which is an alias to `findAll`, you can find its documentation [here](http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance).

**Comment by jblaketc** [comment]
Ah that was it, thanks dude. 

I had to do something like this to get it to deal with the UTC times properly, so I don't know if this is even how you handle it, but adding date filtering to the docs might be helpful. 

````javascript
if(req.query.filter.CreatedOn) {
						req.query.filter.CreatedOn = {$between: [
							moment(new Date(req.query.filter.CreatedOn)).add(1, "day").startOf("day").utc().format("YYYY-MM-DDTHH:mm:ss"),
							moment(new Date(req.query.filter.CreatedOn)).add(1, "day").endOf("day").utc().format("YYYY-MM-DDTHH:mm:ss")
						]};
					}
````
