### ISSUE TITLE
Confusion about "start" and "complete" milestones

### ISSUE THREAD

**Issue by cperryk** [dchester/epilogue#180]
In the [documentation](https://github.com/dchester/epilogue/blob/master/docs/Milestones.md), the `start` milestone is described as `ran at the beginning of the request.` The `complete` milestone is described as `request completed`. It seems like these milestones should be available on all controller actions, but the docs state: `Only send is defined for all actions.` Indeed, doing `resource.list.start.before(fnc)` appears to do nothing. Shouldn't the `start` and `complete` milestones be available on all controller actions?

**Comment by mbroadst** [comment]
@cperryk `before` and `after` only apply to milestones which have been defined, they are essentially there you provide you a way to override the behavior of a predefined milestone by the module. If you want to do something on `start` for the list controller, then just do `resource.list.start(func)`

**Comment by cperryk** [comment]
Ahhhh I see. That make sense. Thanks you!
