### ISSUE TITLE
Working with prefixes like /api/v1/users

### ISSUE THREAD

**Issue by Quodnon** [dchester/epilogue#181]
The question is about 'best practice' I suppose.
I'm making a single-server hobby web-app using epilogue.
While planning application routing I'm sticking to concept of 2 'roots' :
-  '/'-root responsible for front-end part  e.g site.com/user/:id handles personal cabinet or user page
-  '/api/v1/' root  hosts epilogue REST endpoint.  '/api/v1/user/:id'  - retrieve JSON

I did try to make it like this
```javascript
let url='api/v1'
let userResource  ={
    model: User,
    endpoints:['/users','/user/:id'].map(point=>{
        return url+point}),
    excludeAttributes:['password','slt','login']
}

```
But it didn't work. 
Finally:
1. Is it possible or planned to support endpoint naming as `/api/v1/users/:id` ?
2. Am I doing it wrong (at first glance of course)  and API and web servers should be separated?

Thank you

**Comment by mbroadst** [comment]
@Quodnon can you try prefixing the url with `/`, so its:
```
let url='/api/v1'
let userResource  ={
    model: User,
    endpoints: ['/users','/user/:id'].map(point=> url + point),
    excludeAttributes: ['password', 'slt', 'login']
}
```

**Comment by Quodnon** [comment]
:smile:  My bad. Now it works perfectly fine. 
~~maybe 'cause it was 5a.m~~
