### ISSUE TITLE
Filtering via context.criteria, how to override limit

### ISSUE THREAD

**Issue by omayhemo** [dchester/epilogue#188]
Hello again,

I'm adding a serverside filter to context.criteria.  How do I override the default limit to return more entities in the collection?

Thanks

**Comment by mbroadst** [comment]
The settings used can be found here: https://github.com/dchester/epilogue/blob/master/lib/Controllers/list.js#L36

As you can see it either takes a query item `count` or a property called `count` in the context (with priority to the context). If you set up a milestone (e.g. `fetch.before`) you can set the `count` property on the passed context to override the default count of 100.

**Comment by omayhemo** [comment]
As always, thanks for your prompt response.

**Comment by omayhemo** [comment]
Looks like there's a hard limit of 1000 as seen here:
https://github.com/dchester/epilogue/blob/master/lib/Controllers/list.js#L44

Anyway around this?

**Comment by mbroadst** [comment]
Doesn't seem to be, but a PR would be welcome!

**Comment by omayhemo** [comment]
Ok, I've created the pull request, simply pulling out that hard limit.
Thanks
