### ISSUE TITLE
error design

### ISSUE THREAD

**Issue by mbroadst** [dchester/epilogue#27]
Hi guys, this is more of a discussion "issue". I wanted to work out detailed rules for what our errors look like in epilogue. As of right now we have a few cases:
- If ever an instance is not found, we return a status code 404, and an error object (though this differs in a number of places in terms of implementation):

```
HTTP/1.1 404
{ error: 'not found' }
```
- If a validation error occurs we return a status code 400 and an error object that kind of looks like:

```
HTTP/1.1 400
{
  error: {
     < full sequelize ValidationError error object >
  }
}
```
- If a unique constraint error occurs, we return 400 and the sequelize DatabaseErrorObject

```
HTTP/1.1 400
{
   error: {
       < full sequelize DatabaseError object >
   }
}
```
- If anything generally goes wrong we return a 500 status code and whatever error pops up from sequelize:

```
HTTP/1.1 500
{
    error: {
        < some sequelize Error object, probably a DatabaseError object >
    }
}
```

It seems that at least we are consistent with returning the "error" object, but that perhaps we could help users of epilogue out by formalizing the error object a little more. I propose we stick to a standard error object for all types of errors:

```
HTTP/1.1 400 or 500
{
    error: {
        message: 'some message',
        fields: {
            // if they exist for e.g. validation errors
        }
    }
}
```

I think this is a better approach for a couple of reasons:
1. We never respond with the full sequelize error, which in many cases has the full attempted sql statement (which you don't want to expose to outsiders)
2. Users of the api can always count on at least an 'error.message' being there, rather than having to check whether the result of an action was a string or an object

Alternatively, we could go with a far more "RESTful" approach and try to convey the information as much as possible through status code and headers. In this case we could for instance:
- assume that anything in the 400's or 500's is an error, so...
- omit the error object completely, ending up with something like:

```
HTTP/1.1 400 or 500
{
    message: 'some message',
    fields: {
        // if validation errors occurred
    }
}
```

What do you guys think?

**Comment by bradisbell** [comment]
Have you considered adding the status code in a `status` field (or similar) in the error object?  This enables better support for JSON-P, but might be a non-issue these days thanks to better CORS support making JSON-P irrelevant.  This isn't a need I have specifically, but one I've ran into... just throwing it out there for discussion.

**Comment by mbroadst** [comment]
@bradisbell we made the step forward to unify the error representations and that's as far as it's gone to this point. I agree that status codes are nice in large projects for e.g. translation concerns, but I'm not sure this is something that needs to be fixed in epilogue but rather sequelize itself. If we start making status codes for epilogue we're just continuing a chain that starts with sequelize (sequelize is string matching to generate its own errors, passing those on to us to string match and generate our own codes,  all of this starting with a code from the database - but only on SOME databases heh, etc etc). 

I think the solution is to introduce error codes to sequelize to unify a status code for e.g. unique constraints across database implementations. Once that work is done, we can simply include the code into our messages. I'm sure the sequelize guys would take the patch, they're a great bunch to work with :)
