### ISSUE TITLE
How can we get data with search criteria?

### ISSUE THREAD

**Issue by burakkilic** [dchester/epilogue#28]
Hi;

Thanks for the wonderful library. But Readme could be better.

I have a question. How can we get an object list with a search criteria?

E.g: /items?categoryId=1

Thank you.

**Comment by bradisbell** [comment]
@mbroadst Your change was merged to master, but the package.json version number was not bumped with it.  I installed epilogue from NPM and received version 0.3.2, but that's different than your 0.3.2 in your master branch.  Could you please bump the version number and publish to NPM?  In the mean time, I'll install from the repo directly.  Thank you.

**Comment by mbroadst** [comment]
@bradisbell hey, yeah this made it in after the 0.3.2 release I just haven't bumped the version number in master (I believe this is common behavior, but I can totally see why its confusing). The change targets the 0.3.3 release and is merged into the 0.4.0 branch already.

**Comment by bradisbell** [comment]
That works for me, thank you!

**Comment by breandr** [comment]
@burakkilic how do you get those SQL query logs to show up?

**Comment by mbroadst** [comment]
@breandr if you're running the test suite you can modify this line https://github.com/dchester/epilogue/blob/master/tests/support.js#L53 to be "console.log" instead of false. It would be the same in your own project, it's just enabling sequelize logging

**Comment by breandr** [comment]
Thanks @mbroadst, I just found it in the Sequelize docs. :)
