### ISSUE TITLE
How can I retrieve Many-to-Many data

### ISSUE THREAD

**Issue by burakkilic** [dchester/epilogue#30]
Hi;

I have many-to-many categories-items relation.

I want to retrieve the items that belongs to a category.

I make a request with "/items?CategoryId=1"

But I am getting 

    "ER_BAD_FIELD_ERROR: Unknown column 'Item.CategoryId' in 'where clause'"

because relationship is saved in category_items table.

How can I retrieve the associated data in many-to-many relationships.

**Comment by burakkilic** [comment]
module.exports = function(sequelize, DataTypes) {

    var Category = sequelize.define('Category', {
        order: DataTypes.INTEGER,
        published: DataTypes.BOOLEAN
    }, {
        associate: function(models) {
            Category.hasMany(models.Category, {
                as: "SubCategories",
                foreignKey: "ParentId"
            });
            Category.hasMany(models.Item);
            Category.hasMany(models.CategoryTranslation);
        },
        tableName: 'categories'
    });
    return Category;
    };


    module.exports = function(sequelize, DataTypes) {

    var Item = sequelize.define('Item', {
        code: DataTypes.STRING,
        price: DataTypes.DECIMAL(10,2),
        sortOrder: { type: DataTypes.INTEGER, defaultValue: false},
        image: DataTypes.STRING
    }, {
        associate: function(models) {
            Item.belongsToMany(models.Category);
            Item.hasMany(models.ItemTranslation);
        },
        tableName: 'items'
    });

    return Item;
    };

**Comment by mbroadst** [comment]
@burakkilic thank you for the models, I will be out of town for the next ten days but will try to incorporate these into tests asap.

**Comment by burakkilic** [comment]
Thanks @mbroadst

**Comment by dchester** [comment]
We could theoretically add support for something like `/categories/:category_id/items`, but what about just making it work how @burakkilic expected?  We could augment existing routes to support associations, so for example `/items?category_id=1` would just do the right thing.  That seems simpler to me at least.  

Either way, I wonder if we might want to require that users explicitly opt-in to enable/expose these traversals with something like:

```javascript
var items = epilogue.resource({
    model: Item,
    endpoints: ['/items', '/items/:id'],
    associations: [Category]
});
```

**Comment by mbroadst** [comment]
Well, I haven't had a chance to take a good look at it yet, but to a certain degree just passing the right models into the "includes" should work as-is. I might be reading the initial question incorrectly though. I would try:

```
var items = epilogue.resource({
    model: Item,
    endpoints: ['/items', '/items/:id'],
    include: [Category]
});
```

What I'd ideally like to do in the future for all associations is:
  * drop the need for adding "includes" (though still support it the way it currently works)
  * opt-in for "auto associations" (maybe just "autoAssociate: true" in the factory or something), since we already have all the relevant associative information from the model the resource is created for.

**Comment by mbroadst** [comment]
@burakkilic ping, have you tried my suggestion?

**Comment by breandr** [comment]
@mbroadst could you create an issue for us to track the progress of the association routing feature?

**Comment by mbroadst** [comment]
@breandr looks like someone beat both of us to it: https://github.com/dchester/epilogue/issues/34. I'll track the work there
