### ISSUE TITLE
A full example

### ISSUE THREAD

**Issue by shaneveeg** [dchester/epilogue#33]
Would you be willing to provide a full working code example?

I'm attempting to use Epilogue with Sequelize with Express and there are conflicting conventions for how to organize models and controllers (or lack thereof).  

So far I can get working code from the express and sequelize examples, but not with Epilogue. I'm sure I'm just not cutting out the right parts of the parent applications since epilogue handles much of the functionality in those examples.

It would be very helpful if the readme had a full code example for a simple app like a modification of the the task list example Sequelize gives.

**Comment by mbroadst** [comment]
Documentation is definitely on the roadmap here, providing an example using the task list is a great idea. In the meantime, the test suite should provide a pretty good idea of how to set up sequelize + epilogue + express or restify. I've tried to make the tests as self-documenting as possible, hopefully you can get a head start there before a more comprehensive example is provided.

Take a look at:
  * https://github.com/dchester/epilogue/blob/master/tests/support.js
  * https://github.com/dchester/epilogue/blob/master/tests/resource/resource.test.js#L22

**Comment by codebased** [comment]
I have also started using epilogue. However, I am also struggling to start listening end points.
 

TypeError: Object User has no method 'find'
   at Read.fetch (/ Documents/gits/tm/node_modules/epilogue/lib/Controllers/read.js:42:6)

**Comment by mbroadst** [comment]
@shaneveeg were you able to figure out your problem? Would you perhaps be interesting in committing back what you learned as a tutorial here? @codebased I believe your case is simple enough to be covered by the "example" on the main page, you just have a typo (which we'll address in the other ticket).  

Extending the sequelize example is incredibly easy, I just don't think I should go and copy the whole thing. Last night I included in the 0.3.3 release the ability to specify just a model to epilogue's resource factory method btw so now you can just do this (using their example):

if you had models/index.js (per the example), you could do:
```
var epilogue = require('epilogue'),
      models = require('./models'),
      resources = [];

Object.keys(models).forEach(function(modelName) {
    resources.push(epilogue.resource({ model: models[modelName] }));
});
```

This is a very simple case, but you might want to add a class method to your sequelize model (like they do with associate) to include e.g. epilogue middleware/override milestones, or change the endpoints, or specify which actions to use, etc.

I hope this helps a little bit, maybe together we could work on some documentation?

**Comment by shaneveeg** [comment]
No, unfortunately I moved onto another option.  Sails in this case.  I was having a hard time with sequelize more than anything and found that waterline did what I needed.  

Thanks for checking in though.  I would have contributed if I had stuck with it.

**Comment by codebased** [comment]
great it has started working and your above approach with resource works well too. I will write an essay and post you for your approval.

**Comment by edthedev** [comment]
The basic example on the main page does not result in a working API.

Many lines necessary are missing, but even adding the implied lines doesn't result in an API being served.

In the very first example in README.md:
<pre>
var rest = require('epilogue');

rest.initialize({
    app: app,
    sequelize: sequelize
});
</pre>

The example is already incomplete, as app was never defined. Presumably, this line from the Express tutorial should have been included:

<pre>
var app = express();
</pre>

**Comment by payne8** [comment]
Something else that would be helpful to see as an example, is how to reference or manipulate the data before it is sent as a response. For example I have a Users table and a users endpoint. But I don't want to return the password of the user. I can tell from the readme that I should use users.list.data(f) but I am not sure how to reference the data in order to manipulate it.

Thanks for the awesome library by the way it is really cool and really powerful.

**Comment by mbroadst** [comment]
sorry guys this took far longer than it should have, committed in: b5d78e0c62c9cf7ce986d5e2afa9c564b776c5d1

@payne8 you'll definitely want to use milestones for this, depending on what controller you're looking to modify you'd do something like:

```javascript
users.list.send.before(function(req, res, context) {
    context.instances.forEach(function(instance) {
        delete instance.password;
    });

    context.continue();
});
```

**Comment by payne8** [comment]
Thank you @mbroadst. I was able to figure out a way to do it by reading the tests. I will probably migrate to the .send.before milestone rather than the one I am currently using though.
