### ISSUE TITLE
TypeError: Object User has no method 'findAndCountAll'

### ISSUE THREAD

**Issue by codebased** [dchester/epilogue#35]
What wrong I am doing with this code: 

var rest = require('epilogue');
var express = require('express');
var models = require("../models");

var app = express();

rest.initialize({
    app: app,
    sequelize: models.sequelize
});

var users = rest.resource({
    model: "User",
    endpoints: ['/users', '/users/:id']
});

app.listen(3002, function() {
    console.log("✔ Express server listening on port %d in %s mode", 3002, app.get('env'));
});

I have created user model as : 

"use strict";

module.exports = function(sequelize, DataTypes) {
    var User = sequelize.define("User", {
        username: DataTypes.STRING,
        password: DataTypes.STRING,
        active: DataTypes.BOOLEAN
    }, {
        classMethods: {
            associate: function(models) {
                User.hasMany(models.Post)
            }
        }
    });

    return User;
};

Using index.js I am initialising all models present in the models folder.

I believe the problem is with this line:     model: "User", but I don't know how to get the model here  now.

I am getting this error:

TypeError: Object User has no method 'findAndCountAll'
   at List.fetch (//Documents/gits/tm/node_modules/epilogue/lib/Controllers/list.js:89:6)

**Comment by mbroadst** [comment]
Hey, you have two problems here. First you aren't passing a proper model instance into the resource factory method, and secondly you don't provide a way to access the models you create. You'll want something like:
```
var users = rest.resource({
    model: models.User,
    endpoints: ['/users', '/users/:id']
});
```

making sure that you export the "User" model in your models file. Actually, with the latest release (0.3.3) you don't even need to specify the endpoints for the simple case.

**Comment by codebased** [comment]
Awesome work.
it was my fault obviously!!!

After debugging I found the path where models are stored.
var db = require("../models");
var users = rest.resource({
    model: db.sequelize.models.User,
});

This is the first time I have started using node and with the help of epilogue, it has started working straightaway.
