### ISSUE TITLE
Promise over eventemitter - warning.

### ISSUE THREAD

**Issue by codebased** [dchester/epilogue#36]
Great start with epilogue. I am understanding internals now and hopefully will be able to contribute.

Have you got a chance to get away from these warnings:

EventEmitter#success|ok is deprecated, please use promise-style instead.
EventEmitter#failure|fail|error is deprecated, please use promise-style instead.

express deprecated res.json(status, obj): Use res.status(status).json(obj) instead ../../node_modules/epilogue/lib/Controllers/read.js:45:13

**Comment by mbroadst** [comment]
@codebased these errors are actually specific to epilogue, and they are fixed in epilogue master now that I've moved our required sequelize version to sequelize 2.0.0+ (its on rc7 now, the full release should be out shortly). Epilogue 0.3.x will still target sequelize 1.7.x
