### ISSUE TITLE
Limit search to some columns (PostgreSQL error)

### ISSUE THREAD

**Issue by MarZab** [dchester/epilogue#40]
PostgreSQL doesn't like LIKE % queries on numeric fields, as every row has atleast a id, this is a problem.

The soultion would be to either only query string fields or allow field selection for full text search, below is a snippet that does the latter.

```javascript
tags.list.fetch.before(function (req, res, context) {

    if (req.query.q) {
        var search = [];
        ['name', 'slug', 'category', 'description'].forEach(function(attr) {
            var item = {};
            item[attr] = { like: '%' + req.query.q + '%' };
            search.push(item);
        });

        context.criteria = models.sequelize.or.apply(null, search);
    }

    delete req.query.q;
    return context.continue();
});
```

great plugin, rock on

**Comment by mbroadst** [comment]
@MarZab search customization merged with 5aa6e3d81093c679c5adcac5be348d4dfb53bd46, thanks!
