### ISSUE TITLE
Criteria not added to context object

### ISSUE THREAD

**Issue by TheMallen** [dchester/epilogue#41]
I was confused as to why the context.criteria object was always empty in read, as It seemed to me that it would make sense for it to contain the id parameter during a request to something like `GET /api/users/1`.

Well, it seems that context.criteria is never touched in the fetch method at all.

```javascript
// lib/controllers/read.js
Read.prototype.fetch = function(req, res, context) {
  var model = this.model,
      endpoint = this.endpoint,
      criteria = {},
      include = this.include,
      includeAttributes = this.includeAttributes,
      options = {};
     ...
// later
      if (!instance) {
        res.status(404);
        context.error = { message: 'not found' };
        return context.continue();
      }

      context.instance = instance;
      return context.continue();
```

So, as you can see the `context.criteria` object is never assigned. I am not sure why this would be intentional so I assume it is a bug. I know in my case, it is essential to be able to extract the parameters in middleware for auth purposes.

You can [check for yourself](https://github.com/dchester/epilogue/blob/master/lib/Controllers/read.js#L19)

I'll open a pull request later today as the fix seems trivial. I'll check the other controllers as well. Maybe I can find time to write tests as well, but that is more iffy.

**Comment by mbroadst** [comment]
good catch! fixed in 5d95ff67d228f38b3f897b2a57c11914d3e62724

**Comment by TheMallen** [comment]
Hah! Beat me to it.

**Comment by mbroadst** [comment]
:smile: I'm on an "epilogue day" here
