### ISSUE TITLE
Documentation typo for `context.continue`

### ISSUE THREAD

**Issue by bradisbell** [dchester/epilogue#52]
In the [documentation for Customize Behavior](https://github.com/dchester/epilogue#customize-behavior), there are a couple examples where this line is used:

```
return context.continue;
```

This doesn't result in continuing.  Presumably, some parenthesis are missing.

```
return context.continue();
```

**Comment by mbroadst** [comment]
@bradisbell are you using master? the new promise style allows both parenthesis and not to continue

**Comment by bradisbell** [comment]
Nope, I was using 0.4.0.  Thanks!
