### ISSUE TITLE
Exclude some fields from response

### ISSUE THREAD

**Issue by cniaulin** [dchester/epilogue#60]
Hi,

I would like to exclude some fields from the response. I did not find a clear method for that.
At the moment, for the read method, I delete fields from instance.dataValues on the middleware read.send.before. That work well however if it is a getter for this field, I still get the value returned by the getter.
Is it a better way to do that ?

**Comment by mbroadst** [comment]
@cniaulin read.send.before is the right place to do it. ```context.instance``` is what will be serialized to json as per the base rule for sending [here](https://github.com/dchester/epilogue/blob/master/lib/Controllers/base.js#L67). I haven't played around with an instance using getters and setters (perhaps you can submit a test case for this?), but it should be enough to, e.g.: 
'''
delete instance.attribute;
delete instance.dataValues.attribute;
'''

If that doesn't work, you can convert the object to json and replace ```context.instance``` with the new value.

**Comment by mbroadst** [comment]
@cniaulin did that work for you?

**Comment by mbroadst** [comment]
please reopen if you still have a problem
