### ISSUE TITLE
Automatic documentation

### ISSUE THREAD

**Issue by treefort** [dchester/epilogue#79]
Are there any good libraries out there for automatically generating documentation based on epilogue resources?

**Comment by mbroadst** [comment]
@treefort this is something I've been interested in for some time. Take a look at [this](http://dev.mlsdigital.net/posts/apis-specs-and-docs-oh-my-part-3/). They are using respectify, and generating docs + endpoint validation. I think it's a great start, and would be absolutely pro any attempts to make our module work better with that

**Comment by treefort** [comment]
Thanks for the info, @mbroadst!

**Comment by bixibu** [comment]
@treefort Did you have something working for auto-generated doc ? 

I tried http://apidocjs.com and swagger (and even a link between ther two https://github.com/fsbahman/apidoc-swagger) but it's a pain and redondant task to duplicate manually the rest api provided by epilogue :/

**Comment by philotas** [comment]
@jscti 
What did you end up doing?
