### ISSUE TITLE
add ability to pass in "include" to context for relational mapping in list results

### ISSUE THREAD

**Issue by mbroadst** [dchester/epilogue#8]
Hi,
I tried to do this on my own tonight and failed. I wanted to be able to something like this:

```
var users = rest.resource({
    model: database[model],
    endpoints: ['/rest/users', '/rest/users/:id']
});

users.list.fetch.before(function(req, res, context) {
    context.include = [ Address ]
    context.continue();
});
```

the idea being that if you have a relation between the two models (say Address.belongsTo(User) for instance), you could modify the list method to return something like: 

```
{
    name: "John",
    email: "john@gmail.com",
    address: {
        something: "or other";
    }
}
```

It was easy enough to add the "include" property to context and inject it into the "findAll" in list.js, however, when I actually ran the unit test I put together it said that users and addresses were not related. I had basically copied your tests/resource.js and replaced the hasMany relation with a belongsTo, and that's about where I quit.

Any ideas how to get this working? I would provide a patch but its literally something like four lines of code.

**Comment by bradisbell** [comment]
This would be a great feature.  Did it ever land in a release?  The comment from last March seems to indicate it did, but I don't see anything in the readme, and the example from @mbroadst doesn't do anything.  I'm using v0.3.2 from NPM.

**Comment by mbroadst** [comment]
@bradisbell yes this feature was merged in and will work, but is generally supported by passing it in to the resource definition like so:

```
var userResource = epilouge.resource({
    model: models.User,
    include: [models.Address],
    endpoints: ['/rest/users', '/rest/users/:id']
});
```

This include basically aliases to sequelize's include, so you can do stuff like:

```
include: [models.Address, { model: models.Person, as: 'peeps' }]
```

and all that jazz. My intention, based on the last issue brought up, is to provide this for legacy use but to add a feature to opt into "auto-association", pulling in all related associations and potentially new endpoints (like "user/:id/address/:id" for instance). This is not going to make it in in the next two weeks though :smile: 

The documentation needs a serious update (as you've probably noticed from other closed issues here there are at -least- two other undocumented features: 'sort' and 'q' query items), if you're interested changes would be gladly accepted. Aside from that, I'm out of the country for the next 10 days, so it'll be a little before I can properly update the documentation. In the meantime, the tests have pretty good coverage of the features provided, and show you how you can use them.

**Comment by bradisbell** [comment]
I would be happy to contribute to this great project, but I'm just now getting my feet wet with Sequelize and epilogue so I will wait until I know what I'm doing.  I'll check out the tests, thanks!  Enjoy your trip!
