### ISSUE TITLE
epilogue swallows test assertion errors when the context returns an error

### ISSUE THREAD

**Issue by johngiudici** [dchester/epilogue#83]
Add the following test to the end of `milestones.test.js` and run the test suite with USE_RESTIFY=1

```
it('should not swallow test exceptions when using restify', function(done) {
  var createErrorMiddleware = {
    create: {
      start: function(req, res, context) {
        return context.error(403, 'Forbidden', {});
      }
    }
  };
  var forcedErrorResource = rest.resource({
    model: test.models.User,
    endpoints: ['/exceptionTest', '/exceptionTest/:id']
  });
  forcedErrorResource.use(createErrorMiddleware);
  request.post({
    url: test.baseUrl + '/exceptionTest',
    json: {}
  }, function(error, response, body) {
    expect(1).to.equal(2);
    done();
  });
});
```

The test should error with a message stating that it expected 1 to equal 2. However, this exception gets swallowed somewhere and the test waits until it throws a timeout error. Running mocha with the debug options shows that chai makes it to the point where it should throw the error, but then execution just stops. I've recreated this test in restify itself and I couldn't get it to exhibit this behavior, so I'm convinced the issue is somewhere in epilogue. I'm at a loss. Any advice is appreciated.

Running node v0.12.4.

**Comment by mbroadst** [comment]
looks like it passes:
https://travis-ci.org/dchester/epilogue/builds/75160605

anything else accidentally left configured in your environment? (I modified the test to verify the status code and message, but that shouldn't make a difference)

**Comment by johngiudici** [comment]
For some reason, it actually does make a difference. Successful checks move along just fine. Please change the status code comparison to be something like `expect(response.statusCode).to.eql(400)` so that you force a failure. I just upgraded to 0.12.7 and the same thing happens.

**Comment by mbroadst** [comment]
Ah yeah I see it now. Looks like if you replace the `throw error`  with `return Promise.reject(error);` [here](https://github.com/dchester/epilogue/blob/master/lib/Controllers/base.js#L154) then it works. Restify must break exceptions because bluebird handles them properly for sure...

I'm okay with you replacing that outright (it seems to pass all other tests with this change), or checking if you're running restify to use that path, throw otherwise. Not quite sure how you'd write a test for that, but extra cookies if you can :)

**Comment by johngiudici** [comment]
Ya know, I looked at that line and something told me it didn't look right, and I couldn't figure out why so I forgot about it lol. I'll take a look at this tomorrow an see if there's a clearer way of writing that.

**Comment by mbroadst** [comment]
No it totally DOES look right, we should _strive_ to use throw semantics when using promises, however something restify is doing to set up their routes is breaking that behavior (tsk tsk, but I have no time to figure that ish out). I think the proposed `Promise.reject(error)` is the best (and perhaps only way atm) to handle this for restify.

**Comment by johngiudici** [comment]
Looks like restify is setting up a domain [here](https://github.com/restify/node-restify/blob/master/lib/server.js#L948) and catching its events [here](https://github.com/restify/node-restify/blob/master/lib/index.js#L144). I'm really unclear on how domains work, so the best solution I've come up with is to jam the mocha error handler into the server domain inside support.js with

```
TestFixture.server.on('uncaughtException', function (req, res, route, e) {
  process.listeners('uncaughtException')[0].call(this, e);
});
```

That seems really tacky though. Any better ideas?

**Comment by mbroadst** [comment]
Is this for the test case, or for solving the actual problem? If the latter, I say just go with the `Promise.reject` suggested above - all tests pass afaict

**Comment by johngiudici** [comment]
PR up. Checking for `process.domain` should be enough to tell if we're using restify or express.
