### ISSUE TITLE
Problem when trying to add a custom middleware function in addition of epilogue middleware (on top of restify)

### ISSUE THREAD

**Issue by xderoche** [dchester/epilogue#92]
Hi guys,

Thank you for building this useful lib :) ! I recently decided to use it (version 0.5.2) in a project with restify (4.0.0).

I encounter some problem when I try to add a simple middleware function that allows CORS. If I don't add my middleware function, call to the resources return the expected result, i.e., this code works (no surprise!) : 

```javascript
var server = restify.createServer();
server.use(restify.queryParser());
server.use(restify.bodyParser());

epilogue.initialize({
  app: server,
  sequelize: sequelize // defined somewhere else
});

var employeeResource = epilogue.resource({
  model: employee // defined somewhere else
});

server.listen(8080);
```

Now, things go much more worse if I add the function. Description of symptoms :

1- This code below (that adds my middleware function **before** epilogue initialization)) makes the call to the ressource returns {"code":"InternalError","message":"\"name\" and \"value\" are required for setHeader()."}

```javascript
var server = restify.createServer();
server.use(restify.queryParser());
server.use(restify.bodyParser());

server.use(function (req, res, next) {
   res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
   res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
   res.setHeader('Access-Control-Allow-Headers', 'Authorization, X-Requested-With, Content-Type');
   next();
});

epilogue.initialize({
  app: server,
  sequelize: sequelize // defined somewhere else
});

var employeeResource = epilogue.resource({
  model: employee // defined somewhere else
});

server.listen(8080, () => {
    console.log('listening at %s', server.url);
});
```

2 - If I add my middleware function **after** epilogue initialization, it avoids symptom (1), but the  Access-Control-Allow-Origin header is not added to the response, making my call fail with the traditionnal javascript error "XMLHttpRequest cannot load http://localhost:8080/employees. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin [...] is therefore not allowed access."

```javascript
var server = restify.createServer();
server.use(restify.queryParser());
server.use(restify.bodyParser());

epilogue.initialize({
  app: server,
  sequelize: sequelize // defined somewhere else
});

var employeeResource = epilogue.resource({
  model: employee // defined somewhere else
});

server.use(function (req, res, next) {
   res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
   res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
   res.setHeader('Access-Control-Allow-Headers', 'Authorization, X-Requested-With, Content-Type');
   next();
});

server.listen(8080, () => {
    console.log('listening at %s', server.url);
});
```

3- If I use two variables to store reference to restify object (like I found in some example samples of epilogue) and declare my middleware function **before** epilogue stuffs, it works for a valid request, but return CORS error for a wrong one (I tested to call an unknown resource).

NB : This pattern with the use of two variables seems very weird from the point of view of users :)...it does not sound like a very good practice for an API. Would it be a way to make epilogue evolve to avoid the side effects that makes this pattern mandatory ? If such a way exists (must be ^^), maybe this NB would go in the pull requests list !

```javascript
var app, server;
app = server = restify.createServer();
app.use(restify.queryParser());
app.use(restify.bodyParser());

server.use(function (req, res, next) {
   res.setHeader('Access-Control-Allow-Origin', req.headers.origin);
   res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
   res.setHeader('Access-Control-Allow-Headers', 'Authorization, X-Requested-With, Content-Type');
   next();
});

epilogue.initialize({
  app: app,
  sequelize: sequelize // defined somewhere else
});

var employeeResource = epilogue.resource({
  model: employee // defined somewhere else
});

server.listen(8080, () => {
    console.log('listening at %s', server.url);
});
```

I have the feeling that this might come from a miscall of the next() continuation function inside epilogue.

Thank you in advance for your answers !
Cheers

**Comment by mbroadst** [comment]
I think you have two issues here:
  * you should be using `restify.CORS()` rather than doing all of that by hand
  * we actually include a `Content-Range` header as part of the ListController, to give the client hints about stuff like pagination.

In a local project I am using this to solve the problem (before epilogue's initialization, but it shouldn't really matter):
```
server.use(restify.CORS({
  headers: ['content-range']
}));
```

**Comment by xderoche** [comment]
Thank you for your answer.

After some more look at my problem, I realize that on the 3 encountered problems I thought to be symptoms of the issue, two of them were not.

- Fake-symptom (1) : req.headers.origin is null when resource is called with curl, the returned error is normal.
- Fake-Symptom (3)  : restify does not call the whole chain of handler when treating an error. My CORS Headers was not added. The same happens with the CORS extension of restify.

This code does the job well : 

```javascript
server.pre(function (req, res, next) {
   let origin = (req.headers.origin == null) ? '' : req.headers.origin;
   res.setHeader('Access-Control-Allow-Origin', origin);

   res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
   res.setHeader('Access-Control-Allow-Headers', 'Authorization, X-Requested-With, Content-Type');
   next();
});
```

Anyway, the symptom (2) still might be revealing a bug in epilog. In my case, if a hander is declared after epilogue initialization, it is not called. 

```javascript
var app, server;
app = server = restify.createServer();
app.use(restify.queryParser());
app.use(restify.bodyParser());

server.use(function (req, res, next) {
   console.log('before'); // ok
   next();
});

epilogue.initialize({
  app: app,
  sequelize: sequelize // defined somewhere else
});

server.use(function (req, res, next) {
   console.log('after'); // /!\ never reached when resource is called
   next();
});

var employeeResource = epilogue.resource({
  model: employee // defined somewhere else
});

server.listen(8080);
```
