### ISSUE TITLE
Filter by boolean value not possible as it is interpreted as string

### ISSUE THREAD

**Issue by makrolabs** [dchester/epilogue#98]
Given the model:

    var Task = sequelize.define("task", {
        archived: Sequelize.BOOLEAN
    });

The following epilogue route:

    /epilogue/tasks?archived=false

does not work. It throws:

    {"message":"\"false\" is not a valid boolean","errors":[]}

It seems the value is interpreted as a string and never converted.

**Comment by mbroadst** [comment]
fixed in 0fff476ac179418efbe58fdbe32eeff39c70aab5
